import { AnimatePresence, motion } from "framer-motion";
import { Phone, X } from "lucide-react";
import { useEffect, useState } from "react";
import { Button } from "./ui/button";

export function ContactPopup() {
  const [open, setOpen] = useState(false);
  useEffect(() => { const key = `peetham-popup-${new Date().toDateString()}`; let timer: ReturnType<typeof setTimeout> | undefined; if (!localStorage.getItem(key)) timer = setTimeout(() => setOpen(true), 2000); return () => { if (timer) clearTimeout(timer); }; }, []);
  const close = (remember = false) => { if (remember) localStorage.setItem(`peetham-popup-${new Date().toDateString()}`, "hidden"); setOpen(false); };
  return <AnimatePresence>{open && <motion.div className="modal-backdrop" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} role="dialog" aria-modal="true" aria-label="Request astrology guidance"><motion.div className="contact-modal" initial={{ opacity: 0, scale: .96, y: 20 }} animate={{ opacity: 1, scale: 1, y: 0 }} exit={{ opacity: 0, scale: .97 }}><button className="modal-close" onClick={() => close()} aria-label="Close"><X/></button><span className="eyebrow">Personal guidance</span><h2 className="mt-4 font-display text-3xl font-bold">Need Astrology Guidance?</h2><p className="mt-3 text-muted-foreground">Talk to our team for astrology consultations, Pujas, Vastu, Muhurthams and spiritual guidance.</p><form className="mt-6 grid gap-3" onSubmit={(e) => { e.preventDefault(); close(true); }}><label>Name<input required placeholder="Your name"/></label><label>Mobile number<input required inputMode="tel" placeholder="Your mobile number"/></label><Button type="submit">Request callback</Button></form><a className="mt-3 flex items-center justify-center gap-2 text-sm font-bold text-temple" href="tel:+919000985000"><Phone size={16}/> Call 90009 85000</a><label className="mt-5 flex items-center gap-2 text-xs text-muted-foreground"><input type="checkbox" onChange={(e) => e.currentTarget.checked && localStorage.setItem(`peetham-popup-${new Date().toDateString()}`, "hidden")}/> Don’t show this again today</label></motion.div></motion.div>}</AnimatePresence>;
}